import Head from "next/head";
import AppHeader from "./AppHeader";
import { ReactElement, useState } from "react";
import dynamic from "next/dynamic";

interface LayoutProps {
  children: ReactElement;
}

const LoginModal = dynamic(() => import("./LoginModal"), { ssr: false });

export default function Layout({ children }: LayoutProps) {
  const [toggleModal, setToggleModal] = useState<boolean>(false);

  return (
    <section className="flex min-h-screen w-screen flex-col bg-[#F2F2F2]">
      <Head>
        <title>Tweeter - Twitter clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppHeader setToggleModal={setToggleModal} />
      {children}
      <p className="mt-auto px-3 pb-5 text-center text-sm text-gray-400">
        created by
        <span className="font-semibold underline"> Arafat Islam</span> -
        devChallenges.io
      </p>
      <LoginModal toggleModal={toggleModal} setToggleModal={setToggleModal} />
    </section>
  );
}
