import Head from "next/head";
import AppHeader from "./AppHeader";
import { ReactElement, createRef } from "react";

interface LayoutProps {
  children: ReactElement;
}

export default function Layout({ children }: LayoutProps) {
  return (
    <section className="min-h-screen overflow-x-hidden bg-[#F2F2F2]">
      <Head>
        <title>Tweeter - Twitter clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppHeader />
      {children}
      <p className="mb-5 text-center text-sm text-gray-400">
        created by
        <span className="font-semibold underline"> Arafat Islam</span> -
        devChallenges.io
      </p>
    </section>
  );
}

// const Layout = forwardRef((ref,props) => {
//   return (
//     <section className="min-h-screen overflow-x-hidden bg-[#F2F2F2]">
//       <Head>
//         <title>Tweeter - Twitter clone</title>
//         <meta name="description" content="Generated by create-t3-app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <AppHeader />
//       {props.children}
//       <p className="mb-5 text-center text-sm text-gray-400">
//         created by
//         <span className="font-semibold underline"> Arafat Islam</span> -
//         devChallenges.io
//       </p>
//     </section>
//   );
// });

// export default Layout;
